This commit was manufactured by cvs2svn to create branch 'avendor'.
Sprout from master 2000-03-23 04:25:31 UTC jose '*** empty log message ***'
Delete:
    lejos/ACKNOWLEDGEMENTS
    lejos/LICENSE
    lejos/Makefile
    lejos/Makefile.common
    lejos/Makefile.config
    lejos/README
    lejos/RELEASENOTES
    lejos/VERSION
    lejos/bin/aux-tvmld
    lejos/bin/tinyvm.srec
    lejos/bin/tvmc
    lejos/bin/tvmld
    lejos/bin/tvmld-emul
    lejos/bin/tvmp
    lejos/examples/robotics/rotator/Rotator.java
    lejos/lib/.anchor
    lejos/src/java/classes/java/lang/ArithmeticException.java
    lejos/src/java/classes/java/lang/ArrayIndexOutOfBoundsException.java
    lejos/src/java/classes/java/lang/Class.java
    lejos/src/java/classes/java/lang/ClassCastException.java
    lejos/src/java/classes/java/lang/ClassNotFoundException.java
    lejos/src/java/classes/java/lang/Cloneable.java
    lejos/src/java/classes/java/lang/Error.java
    lejos/src/java/classes/java/lang/Exception.java
    lejos/src/java/classes/java/lang/NoClassDefFoundError.java
    lejos/src/java/classes/java/lang/NoSuchMethodError.java
    lejos/src/java/classes/java/lang/NullPointerException.java
    lejos/src/java/classes/java/lang/Object.java
    lejos/src/java/classes/java/lang/OutOfMemoryError.java
    lejos/src/java/classes/java/lang/RuntimeException.java
    lejos/src/java/classes/java/lang/StackOverflowError.java
    lejos/src/java/classes/java/lang/String.java
    lejos/src/java/classes/java/lang/StringBuffer.java
    lejos/src/java/classes/java/lang/System.java
    lejos/src/java/classes/java/lang/Thread.java
    lejos/src/java/classes/java/lang/Throwable.java
    lejos/src/java/tools/js/classfile/EClassFileFormat.java
    lejos/src/java/tools/js/classfile/EConstantPool.java
    lejos/src/java/tools/js/classfile/EExtraBytes.java
    lejos/src/java/tools/js/classfile/EPolyClassLoader.java
    lejos/src/java/tools/js/classfile/IConstantPool.java
    lejos/src/java/tools/js/classfile/IConstantPoolEntry.java
    lejos/src/java/tools/js/classfile/IConstants.java
    lejos/src/java/tools/js/classfile/IDumpable.java
    lejos/src/java/tools/js/classfile/IVMInstruction.java
    lejos/src/java/tools/js/classfile/JAttribute.java
    lejos/src/java/tools/js/classfile/JAttributeTable.java
    lejos/src/java/tools/js/classfile/JCPE_Class.java
    lejos/src/java/tools/js/classfile/JCPE_Double.java
    lejos/src/java/tools/js/classfile/JCPE_Dummy.java
    lejos/src/java/tools/js/classfile/JCPE_Fieldref.java
    lejos/src/java/tools/js/classfile/JCPE_Float.java
    lejos/src/java/tools/js/classfile/JCPE_Integer.java
    lejos/src/java/tools/js/classfile/JCPE_InterfaceMethodref.java
    lejos/src/java/tools/js/classfile/JCPE_Long.java
    lejos/src/java/tools/js/classfile/JCPE_Methodref.java
    lejos/src/java/tools/js/classfile/JCPE_NameAndType.java
    lejos/src/java/tools/js/classfile/JCPE_NamedEntry.java
    lejos/src/java/tools/js/classfile/JCPE_RefEntry.java
    lejos/src/java/tools/js/classfile/JCPE_String.java
    lejos/src/java/tools/js/classfile/JCPE_Utf8.java
    lejos/src/java/tools/js/classfile/JCP_Index.java
    lejos/src/java/tools/js/classfile/JClassFile.java
    lejos/src/java/tools/js/classfile/JClassName.java
    lejos/src/java/tools/js/classfile/JCodeAttribute.java
    lejos/src/java/tools/js/classfile/JComponent.java
    lejos/src/java/tools/js/classfile/JConstantPool.java
    lejos/src/java/tools/js/classfile/JConstantPoolEntry.java
    lejos/src/java/tools/js/classfile/JConstructor.java
    lejos/src/java/tools/js/classfile/JExcep.java
    lejos/src/java/tools/js/classfile/JExcepTable.java
    lejos/src/java/tools/js/classfile/JField.java
    lejos/src/java/tools/js/classfile/JFieldTable.java
    lejos/src/java/tools/js/classfile/JIO.java
    lejos/src/java/tools/js/classfile/JIndexTable.java
    lejos/src/java/tools/js/classfile/JMethod.java
    lejos/src/java/tools/js/classfile/JMethodTable.java
    lejos/src/java/tools/js/classfile/JMisc.java
    lejos/src/java/tools/js/classfile/JStatic.java
    lejos/src/java/tools/js/classfile/JTable.java
    lejos/src/java/tools/js/classfile/JUtf8.java
    lejos/src/java/tools/js/tinyvm/BEDataOutputStream.java
    lejos/src/java/tools/js/tinyvm/Binary.java
    lejos/src/java/tools/js/tinyvm/ByteWriter.java
    lejos/src/java/tools/js/tinyvm/ClassPath.java
    lejos/src/java/tools/js/tinyvm/ClassRecord.java
    lejos/src/java/tools/js/tinyvm/CodeSequence.java
    lejos/src/java/tools/js/tinyvm/CodeUtilities.java
    lejos/src/java/tools/js/tinyvm/ConstantRecord.java
    lejos/src/java/tools/js/tinyvm/ConstantValue.java
    lejos/src/java/tools/js/tinyvm/Constants.java
    lejos/src/java/tools/js/tinyvm/EnumerableSet.java
    lejos/src/java/tools/js/tinyvm/ExceptionRecord.java
    lejos/src/java/tools/js/tinyvm/HashVector.java
    lejos/src/java/tools/js/tinyvm/IOUtilities.java
    lejos/src/java/tools/js/tinyvm/InstanceFieldRecord.java
    lejos/src/java/tools/js/tinyvm/LEDataOutputStream.java
    lejos/src/java/tools/js/tinyvm/MasterRecord.java
    lejos/src/java/tools/js/tinyvm/MethodRecord.java
    lejos/src/java/tools/js/tinyvm/OpCodeConstants.java
    lejos/src/java/tools/js/tinyvm/OpCodeInfo.java
    lejos/src/java/tools/js/tinyvm/RecordTable.java
    lejos/src/java/tools/js/tinyvm/Sequence.java
    lejos/src/java/tools/js/tinyvm/Signature.java
    lejos/src/java/tools/js/tinyvm/SpecialClassConstants.java
    lejos/src/java/tools/js/tinyvm/SpecialSignatureConstants.java
    lejos/src/java/tools/js/tinyvm/StaticFieldRecord.java
    lejos/src/java/tools/js/tinyvm/StaticValue.java
    lejos/src/java/tools/js/tinyvm/TinyVM.java
    lejos/src/java/tools/js/tinyvm/Utilities.java
    lejos/src/java/tools/js/tinyvm/WritableData.java
    lejos/src/java/tools/js/tinyvm/WritableDataWithOffset.java
    lejos/src/java/tools/js/tools/GenerateConstants.java
    lejos/src/java/tools/js/tools/ListReader.java
    lejos/src/java/tools/js/tools/TListClasses.java
    lejos/src/java/tools/js/tools/TestClassDumper.java
    lejos/src/javavm/Makefile
    lejos/src/javavm/classes.db
    lejos/src/javavm/classes.h
    lejos/src/javavm/configure.h
    lejos/src/javavm/constants.h
    lejos/src/javavm/download.c
    lejos/src/javavm/exceptions.c
    lejos/src/javavm/exceptions.h
    lejos/src/javavm/interpreter.c
    lejos/src/javavm/interpreter.h
    lejos/src/javavm/language.c
    lejos/src/javavm/language.h
    lejos/src/javavm/limits.h
    lejos/src/javavm/magic.h
    lejos/src/javavm/main.c
    lejos/src/javavm/memory.c
    lejos/src/javavm/memory.h
    lejos/src/javavm/native.c
    lejos/src/javavm/native.h
    lejos/src/javavm/op_arithmetic.hc
    lejos/src/javavm/op_arrays.hc
    lejos/src/javavm/op_control.hc
    lejos/src/javavm/op_conversions.hc
    lejos/src/javavm/op_locals.hc
    lejos/src/javavm/op_logical.hc
    lejos/src/javavm/op_methods.hc
    lejos/src/javavm/op_objects.hc
    lejos/src/javavm/op_other.hc
    lejos/src/javavm/op_skip.hc
    lejos/src/javavm/op_stack.hc
    lejos/src/javavm/opcodes.h
    lejos/src/javavm/rcx.lds
    lejos/src/javavm/signatures.db
    lejos/src/javavm/specialclasses.h
    lejos/src/javavm/specialsignatures.h
    lejos/src/javavm/threads.c
    lejos/src/javavm/threads.h
    lejos/src/javavm/trace.h
    lejos/src/javavm/types.h
    lejos/src/tools/emu-lejos/Makefile
    lejos/src/tools/emu-lejos/tvm.c
    lejos/src/tools/emu-lejos/tvmdownload.c
    lejos/src/tools/emu-lejos/tvmfirmdl.c
    lejos/test/regression/Test00.java
    lejos/test/regression/Test01.java
    lejos/test/regression/Test02.java
    lejos/test/regression/Test03.java
    lejos/test/regression/Test04.java
    lejos/test/regression/Test05.java
    lejos/test/regression/Test06.java
    lejos/test/regression/Test07.java
    lejos/test/regression/Test08.java
    lejos/test/regression/Test09.java
    lejos/test/regression/Test10.java
    lejos/test/regression/Test11.java
    lejos/test/regression/Test12.java
    lejos/test/regression/Test13.java
    lejos/test/regression/Test14.java
    lejos/test/regression/Test15.java
    lejos/test/regression/Test16.java
    lejos/test/regression/Test17.java
    lejos/test/regression/Test18.java
    lejos/test/regression/Test19.java
    lejos/test/regression/Test20.java
    lejos/test/regression/Test21.java
    lejos/test/regression/Test22.java
    lejos/test/regression/Test23.java
    lejos/test/regression/regression.gold
    lejos/test/regression/run-in-rcx-01.sh
    lejos/test/regression/run-in-rcx-02.sh
    lejos/test/regression/run-in-rcx-03.sh
    lejos/test/regression/run-in-rcx.sh
    lejos/test/regression/run.sh